version: '3'
services:
  cveweb:
    container_name: cveweb
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks: ["cveweb"]
    ports: ["8080:8080"]
    volumes:
      - ../package.json:/app/package.json
      - ../src:/app/src

networks:
  cveweb:
